name: "template"

services:
  backend:
    container_name: "pattern-backend"
    image: "local/template/backend"
    build:
      context: backend
    ports:
      - "8080:8080"
      - "8081:8081" # actuator
    environment:
      JAVA_OPTS: >
        -XX:InitialRAMPercentage=50
        -XX:MaxRAMPercentage=75
        -XX:MinRAMPercentage=25
        -XX:MetaspaceSize=128m
        -XX:MaxMetaspaceSize=256m
        -XX:+UseG1GC 
        -XX:MaxGCPauseMillis=200
        -XX:+HeapDumpOnOutOfMemoryError 
        -XX:HeapDumpPath=/heapdump.hprof
      SPRING_OPTS: "--spring.profiles.active=local"