openapi: 3.0.1
info:
  title: Backend API
  description: Backend API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1'
    description: "Local environment"
tags:
  - name: Hello
    description: Hello World
paths:
  /health:
    $ref: "belgif/common/v1/common-v1.yaml#/paths/~1health"
  /hello/{key}:
    get:
      operationId: helloWorld
      description: First operation in an API for the tests
      summary: Hello world
      tags:
        - Hello
      parameters:
        - name: key
          in: path
          required: true
          description: Key of the greeting message
          schema:
            type: string
            maxLength: 50
            minLength: 1
      responses:
        "200":
          description: Ok
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/HelloWorld"
        "400":
          $ref: "belgif/problem/v1/problem-v1.yaml#/components/responses/InputValidationProblemResponse"
        default:
          $ref: "belgif/problem/v1/problem-v1.yaml#/components/responses/ProblemResponse"
components:
  schemas:
    HelloWorld:
      type: object
      required:
        - message
      properties:
        message:
          type: string